### ISSUE TITLE
示例复制到工程后找不到ADBRuntime命名空间

### ISSUE THREAD

**Issue by eterner2** [OneYoungMean/Automatic-DynamicBone#10]
2019.4.12版本的unity
![H 06DSV{B}8O25LC1CN3JZU](https://user-images.githubusercontent.com/48097124/98364517-e4f84f00-206b-11eb-8bc7-a810f6ce2052.png)

**Comment by OneYoungMean** [comment]
示例需要该库的支持,你需要先导入库文件再导入示例
请尝试:
先克隆该库,然后再unity中打开该库,再将示例文件拖入Assets文件夹下.
如果问题仍然存在,请回复.
