### ISSUE TITLE
某些杆件不能正常工作或不能显示Gizmos

### ISSUE THREAD

**Issue by mikegittester** [OneYoungMean/Automatic-DynamicBone#12]
以下杆件似乎不能正常工作，或者不能显示Gizmos？
- 水平相邻杆件
- 水平网状杆件
- 水平相间杆件
- 放射分布杆件

ADBConstraintReadAndPointControll.cs
- CreationConstraintHorizontal
- CreationConstraintShear
- ...
```
460: void CreationConstraintHorizontal(){
...
471: if (childPointAList[0].isAllowComputeOtherConstraint || childPointBList[0].isAllowComputeOtherConstraint) return;
}
...
```

**Comment by OneYoungMean** [comment]
非常感谢bug的提交!
这是一个很致命的bug,在之前的测试中我没能发现它,我很抱歉.
我正在进一步了解这个bug,稍后我会给出一个详细的解释与道歉.

**Comment by OneYoungMean** [comment]
![image](https://user-images.githubusercontent.com/44113189/111648569-76f43d80-883e-11eb-8835-1dc0690d60a0.png)
感谢bug的提交！我已经简单的完成修复与测试了，希望它不会影响您的工作。
bug来源于一次版本合并，这是一个由於版本合中没有及时处理冲突，导致一些历史遗留的代码被当成了正确的代码在运行。
由於那次意外的合并，该bool值的指向的值被设定成了一个相反的参数，这导致上述的杆件无法正常的工作。
我已经尝试修复了所有与该bool相关的属性，并重新检查了创建杆件的正确性，现在它看起来能够正常工作了。
如果您发现任何可疑的地方，可以继续回复此issue，我会及时检查我的github。
再一次诚恳的抱歉。

**Comment by mikegittester** [comment]
感谢回复。
ADBConstraintReadAndPointControll.cs 引用错误
- ADBRuntimePoint.allowCreateAllConstraint() 方法不存在

**Comment by OneYoungMean** [comment]
感谢指出,请原谅我的失误,我忘记上传了,现在已经修复.

**Comment by mikegittester** [comment]
我认为该问题已经修复了。
