### ISSUE TITLE
运行时，重置所有节点数据并重新运行，虚拟节点会变为普通节点

### ISSUE THREAD

**Issue by mikegittester** [OneYoungMean/Automatic-DynamicBone#13]
再次初始化时，虚拟节点可能存在问题

## 复现方法
1. ADBSetting 中勾选生成虚拟节点
2. 运行
3. 点击”重置所有节点数据并重新运行“
4. 虚拟节点似乎变成了普通节点，并会生成杆件（如水平杆件）

**Comment by OneYoungMean** [comment]
非常感谢您的指出!
我认为这个bug来源自重新生成时,脚本不能识别出创建的节点是上一次创建的virtual节点所导致的.
目前我暂时不能及时修复该错误,正在对项目的底层做一些更改与测试,这个错误可能会与本次测试更改一同修复.
如果这个bug这影响了你进一步的工作,请回复本条issue,我将会优先解决您的问题.
再次感谢您的热心帮助~

**Comment by mikegittester** [comment]
该BUG并不严重，可推后修复。

**Comment by OneYoungMean** [comment]
问题已经修复,请查收,感谢您的提交
