### ISSUE TITLE
碰撞体脚本内的偏移坐标不为实际碰撞体的偏移坐标

### ISSUE THREAD

**Issue by VCMellon** [OneYoungMean/Automatic-DynamicBone#14]
视图中绘制出来的形状体的坐标是和偏移坐标一致，实际的运行时碰撞体的头尾方向偏移坐标为0，但绘制和显示出来的还是原来的坐标
Unity版本：2019.4.17f1
![image](https://user-images.githubusercontent.com/65802731/117579821-a08b6000-b12f-11eb-81a6-eb44b761f140.png)
![image](https://user-images.githubusercontent.com/65802731/117579999-a6ce0c00-b130-11eb-8d0f-9fcbde21bd00.png)

**Comment by VCMellon** [comment]
胶囊体头尾的碰撞范围有点奇怪，会产生虚空碰撞

**Comment by VCMellon** [comment]
错误案例：https://drive.google.com/file/d/1TepqZj8kOApzWGHhkamVZf-8sTGuP5MD/view?usp=sharing

**Comment by OneYoungMean** [comment]
案例已经收到,感谢您的提供.
由于最近工作量很大,所以我无法第一时间查看您的错误案例.
我会在48小时内尽快解决这个问题.为您需要等待而抱歉.

**Comment by VCMellon** [comment]
没事的，你可以先忙你的事情，我暂时先用球形刚体代替

**Comment by OneYoungMean** [comment]
问题已经解决,将会在下一次更新一起提交

**Comment by VCMellon** [comment]
感谢！

**Comment by OneYoungMean** [comment]
问题已经修复,请查收,感谢您的提交
