### ISSUE TITLE
搜索的节点超过3个之后运行就报错，物理效果也没了。

### ISSUE THREAD

**Issue by 31756381** [OneYoungMean/Automatic-DynamicBone#16]
试了好几次 只要搜索的节点超过了3个之后第4个开始就开始报下面错误。
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
名称那些都没错呀，换成4个以内运行就一切正常了。演示场景里面的5-Character-Dance-Test，R1N4_V2_Parker这个Model的效果就看不到，另外的两个都正常。

**Comment by 31756381** [comment]
碰撞体删除后
5-Character-Dance-Test 打开后用存在的名称搜索节点
运行错误提示
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
ADBRuntime.ADBAvatarReader.CaculateAABB (ADBRuntime.ADBConstraintReadAndPointControll[] jointAndPointControlls) (at Assets/ADB Unity Project/Assets/Automatic Dynaimc Bone/Runtime/ADBAvatarReader.cs:68)
ADBRuntime.Mono.ADBRuntimeController.initializeCollider () (at Assets/ADB Unity Project/Assets/Automatic Dynaimc Bone/Runtime/ADBRuntimeController.cs:398)
ADBRuntime.Mono.ADBRuntimeController.Start () (at Assets/ADB Unity Project/Assets/Automatic Dynaimc Bone/Runtime/ADBRuntimeController.cs:127)
也没办法生成碰撞体了。

**Comment by OneYoungMean** [comment]
问题已经收到,我们将会跟进这个问题,并在48小时内回复您

**Comment by OneYoungMean** [comment]
问题已经定位,并得到了解决.
问题原因为错误的下标访问,这个问题在很早之前被修复过,但是错误的合并导致它的发生.
请拉取或者下载最新项目以修复错误,感谢您的提交.

**Comment by 31756381** [comment]
十分感谢，刚才拉取后重新导入问题已经解决。
