### ISSUE TITLE
胶囊碰撞体可能有些bug

### ISSUE THREAD

**Issue by xiangxiangjiang** [OneYoungMean/Automatic-DynamicBone#2]
首先感谢您分享这个插件，谢谢。
我在使用您的插件时，发现使用胶囊碰撞体容易出现衣服褶皱穿模，而且碰撞的范围要比显示的范围大，效果不如用两个球形的代替的好。不知道您是否有遇到这种情况。

**Comment by OneYoungMean** [comment]
我重新检查了一遍collider的碰撞效果,其中并没有出现你所说的collider范围过大的情况,,这可能只是一个小小的误会. 
我想说的是,在高精度的碰撞模式下,它是按照骨骼与胶囊体碰撞(类似于线与胶囊体碰撞)而工作的,在这张图中,我们可以看到, 骨骼是严格与胶囊体相切的.  
![TIM图片20200308085453](https://user-images.githubusercontent.com/44113189/76154652-fc68ec00-611a-11ea-8016-e89823f51891.png)
如果你需要点与胶囊体碰撞,你可以采用fast的碰撞模式,这个模式仅采用点与碰撞体进行运算.  
关于穿模的问题,这个我已经在Q&A当中复述过了,无法包裹mesh的collider会导致小部分的穿模(事实上在自动生成的collider当中这种情况相当普遍),,如果你觉得胶囊体的确不够好,你可以尝试跟换collider,这是很简单的事情.  
祝您使用愉快.
