### ISSUE TITLE
WebGL可以支持吗？或者有类似方案支持WebGL的吗？

### ISSUE THREAD

**Issue by xiezi5160** [OneYoungMean/Automatic-DynamicBone#24]
如果实在支持不了，请问有WebGL平台对应的解决方案吗？
辛苦解惑，拜谢~

**Comment by OneYoungMean** [comment]
来晚的回复~
webGL已经支持,但还没有发布,请关注项目更新哦

**Comment by xiezi5160** [comment]
> 来晚的回复~ webGL已经支持,但还没有发布,请关注项目更新哦

求更新，求求~
