### ISSUE TITLE
Mathematics库需要2019.3以上版本？

### ISSUE THREAD

**Issue by lanqibo** [OneYoungMean/Automatic-DynamicBone#3]
我目前使用的2018.4无法运行啊

**Comment by OneYoungMean** [comment]
代码动不存在对于数学库的引用,低版本可以考虑使用与jobs相对应的math库即可,brust同理.
另外,unity对于在高版本当中的sence在低版本当中可能会有打不开的现象,并且unity没有提供相应的降版本功能,
虽然这并不影响具体的使用,不过考虑到初次接触需要一点参考,建议还是准备一个高版本的unity查看运行情况.
就目前情况,我不打算倒回低版本再重新制作一遍sence,请原谅我的偷懒 :p
