### ISSUE TITLE
如何与环境中其他碰撞器交互

### ISSUE THREAD

**Issue by yangfengzzz** [OneYoungMean/Automatic-DynamicBone#31]
代码中使用了内部的碰撞器类型，但是环境当中其他碰撞器都还是用的Unity内置的物理引擎，这两者如果要交互会怎么做呢？

**Comment by OneYoungMean** [comment]
问题收到.
ADB会将带有ADBColliderReader的Unity Collider转换为内部的碰撞器类型,如果你想让unity的胶囊体/球体/盒与物理骨骼交互,您只需要给目标碰撞体加上ADBColliderReader即可.
如果您想要了解更多信息,可以参考案例0.
祝您生活愉快.

**Comment by OneYoungMean** [comment]
问题收到.
是支持的,ADB仅从碰撞体收集数据,不会修改额外的东西.您只需要将其当成正常的unity碰撞体使用即可.
祝您生活愉快.
