### ISSUE TITLE
运行MikuDanceTest场景的时候出现错误

### ISSUE THREAD

**Issue by ditianxin** [OneYoungMean/Automatic-DynamicBone#4]
InvalidOperationException: ADBRuntime.ColliderRead used in NativeArray<ADBRuntime.ColliderRead> must be blittable.
ColliderRead.isOpen is not blittable (System.Boolean)

Unity.Collections.NativeArray`1[T].IsBlittableAndThrow () (at C:/buildslave/unity/build/Runtime/Export/NativeArray/NativeArray.cs:103)
Unity.Collections.NativeArray`1[T].Allocate (System.Int32 length, Unity.Collections.Allocator allocator, Unity.Collections.NativeArray`1[T]& array) (at C:/buildslave/unity/build/Runtime/Export/NativeArray/NativeArray.cs:76)
Unity.Collections.NativeArray`1[T]..ctor (ADBRuntime.ColliderRead[] array, Unity.Collections.Allocator allocator) (at C:/buildslave/unity/build/Runtime/Export/NativeArray/NativeArray.cs:55)
ADBRuntime.DataPackage.SetColliderPackage (ADBRuntime.ColliderRead[] collidersReadList, ADBRuntime.ColliderReadWrite[] collidersReadWriteList, UnityEngine.Transform[] collidersTransList) (at Assets/Automatic Dynaimc Bone/ADBPackage.cs:52)
ADBRuntime.ADBRuntimeColliderControll.GetData (ADBRuntime.DataPackage& dataPackage) (at Assets/Automatic Dynaimc Bone/ADBRuntimeColliderControll.cs:121)
ADBRuntime.ADBRuntimeController.Start () (at Assets/Automatic Dynaimc Bone/ADBRuntimeController.cs:82)

用的是unity2018.4.14f1版本，谢谢

**Comment by OneYoungMean** [comment]
抱歉,这几天考研复试需要搞复习,所以无法查看场景在2018.4版本运行的具体情况.
报错看起来像是Unity.Collection出了问题,如果要解决,请尝试复制整个项目,在2019以上的版本打开,如果没有报错则可以确认是Collection库进行了改动,请尝试降Collection包的版本.如果仍然出现报错,请复制到该issue下.
对于无法高效解决问题,实在见谅

**Comment by ditianxin** [comment]
感谢回复，
1.升级一下unity，然后再运行一下
2.降低一下collection版本
这两个方法我都测试一下，后面把测试情况反馈一下

**Comment by ditianxin** [comment]
测试下来升级unity到2019.2.19f1是可行的，降低collection库不可行
感谢分享，祝考研顺利，加油

**Comment by OneYoungMean** [comment]
谢谢XD
