### ISSUE TITLE
github留个联系方式呗，不然怎么联系你嘞。

### ISSUE THREAD

**Issue by luxuia** [OneYoungMean/Automatic-DynamicBone#7]
是想找哪个城市哪个方向的工作？

**Comment by OneYoungMean** [comment]
sdl,wsl_(:з」∠)_
我的QQ号是3303609008,想去上海找一个暂时的实习(还要读研)学习一下

**Comment by luxuia** [comment]
这不都快开学了么。我这边是广州做手游的，暂时没有短期的实习哈，抱歉。 做的挺好的，加油。

**Comment by OneYoungMean** [comment]
谢谢大佬的关照了,我会好好努力的QwQ
