### ISSUE TITLE
碰撞体只能选球体和长方体，选择胶囊时会自动变成球体？

### ISSUE THREAD

**Issue by kumopult** [OneYoungMean/Automatic-DynamicBone#8]
角色用的不是humanoid于是手动一个一个添加，结果选不了胶囊……

**Comment by OneYoungMean** [comment]
我甚至都没来得及看,你就把它关上了QwQ

**Comment by OneYoungMean** [comment]
在修改完成脚本之后会导致原来脚本内存储的数据被重置,这个时候Gizmo就会不认帐,不过启动的时候就好了(躺)
