### ISSUE TITLE
MMD模型的问题

### ISSUE THREAD

**Issue by h3166179** [OneYoungMean/Automatic-DynamicBone#9]
普通模型使用还可以，由MMD4Mecanim转换过来的mmd模型生成头发虽然生成成功了，但会出现奇怪的bug，模型位置一移动头发一直朝天左右摆动

**Comment by h3166179** [comment]
顺便问下，有中文的插件版本吗，我看文档都是中文的，拉下来却都是英文的

**Comment by OneYoungMean** [comment]
请提供一下问题模型,并提供一下英文界面相关截图,以帮助我能够更好的协助解决问题,

**Comment by h3166179** [comment]
链接：https://pan.baidu.com/s/1AQ0PSDw2lY1GzmBshp7--w 
提取码：nlni 
放一起了、、、、

**Comment by OneYoungMean** [comment]
我确认我的项目Edtor脚本文件已经更新成中文,如果你项目还是英文,请尝试:
1.删掉原有项目并重新用github desktop下载. 
2.用压缩包下载.  
模型的问题我还在检查当中...

**Comment by OneYoungMean** [comment]
模型没有问题,确认完毕.如果您不喜欢风力,请查看wiki中关于风力的描述.
![QQ截图20201018192558](https://user-images.githubusercontent.com/44113189/96366057-c4795b00-1177-11eb-976f-46956f409fda.png)

**Comment by h3166179** [comment]
好奇怪，我的模型是飞起来的，可能是因为版本不同，我在尝试更新插件。。。

**Comment by OneYoungMean** [comment]
如果没有问题的话,该issue将会被关闭,祝你好运!
